### ISSUE TITLE
Process does not start

### ISSUE THREAD

**Issue by m1hah** [SimonKagstrom/tesla_dashcam_manager#2]
Hi, the process doesn't start. I am using the default tesla-dashcam-manager docker-compose with edited volumes, TZ and arguments: 
`--title_screen_map --gpu --gpu_type=rpi --text_overlay_fmt "{event_timestamp} {event_city}" --layout WIDESCREEN --quality MEDIUM --fps 33`

**Hardware:**
- RPi Z W in a car
- RPi 4 as a footage processor
- NAS as a long-term raw footage storage
- Web server storage for serving the edited files

**Process:**
- RPi Z W offloads the footage to the NAS (working)
- RPi 4 with access to the NAS footage AND web server storage (working)
    - original TeslaCam folder: /mnt/NAS/TeslaCam
    - long term storage: /mnt/NAS/TeslaRaw
    - Webserver: /mnt/WS/TeslaDashcam
- Docker compose is linked with the above folders to docker /app/... folders, when I exec in the docker, I can manipulate the data so the access and chmod is ok

In the /mnt/NAS/TeslaCam folder I can see folders with dates (each event is its own folder).
RPi4 has access to all the data and folders. When the docker container starts, two folders are created inside /mnt/NAS/TeslaCam: "processing" and "work".

After that, nothing happens.

---
If anyone has any idea what I did wrong, please let me know! I am guessing that something is wrong with the folder setup. I have read all the Tesla_dashcam documentation and can't figure it out. Thank you!

**Comment by m1hah** [comment]
Maybe it has to do something with the:
`export trigger_file_any=ARCHIVE_UPLOADED` 

I am using SMB and not rsync.

**Comment by SimonKagstrom** [comment]
Yes, the trigger file is needed, so needs to be added to the RPI zero for it to work if you haven't already done so.

You can try to manually create the file to trigger processing the first time. SMB or rsync should not matter, as long as the files show up - the script simply polls periodically.

Thanks for the very detailed report!

**Comment by m1hah** [comment]
Hi, thank you SimonKagstrom!

The process has now started, but I am facing another issue: output files are 0kb in size and are not readable. It must be some kind of problem in the processing. I get no error or anything, files are moved between the folders like they were meant to.

Arguments tested:
`--title_screen_map --gpu --gpu_type=rpi --text_overlay_fmt "{event_timestamp} {event_city}" --layout WIDESCREEN --quality MEDIUM --fps 33`
`--title_screen_map --gpu --gpu_type=rpi --text_overlay_fmt "{event_timestamp} {event_city}"`

I will look into it a bit more, if I won't be successful, I will try to build my own dockerfile from source. :)

Thank you!

![image](https://user-images.githubusercontent.com/70815607/184690505-abd0b670-b8ea-411c-8f09-39356868fda1.png)

**Comment by SimonKagstrom** [comment]
Strange! That is something I haven't seen.

When debugging, it might be easiest to run the shell in the docker image and mount the source code directory to the container (the -v option). Then it can be started manually, with the latest sources.

On the other hand, unless Tesla dashcam manager passes the wrong arguments, it sounds like it's an issue with Tesla dashcam (the upstream tool).

Thanks for looking into this!

**Comment by m1hah** [comment]
I have now tried to run it with the argument `--no-gpu` and it is now processing the data. CPU is at 100% and I see the "work" directory building slowly.

It works, however, I will need to take a look at why my RPi4 4GB doesn't process when using `--gpu --gpu_type rpi` args. I am using Dietpi in headless mode on my RPi so this might be a simple dependencies issue.
 
![image](https://user-images.githubusercontent.com/70815607/184692814-711fa4f1-b426-4952-9eed-c09a5c5d9dd3.png)

Thank you!

**Comment by SimonKagstrom** [comment]
I'll take a look at mine later tonight. I also use a rpi4, but with raspian and 8G ram. It was a while since I set it up, and perhaps there was some kernel command line option that was used.

**Comment by SimonKagstrom** [comment]
My /proc/cmdline looks like this:

```
pi@rpi4:~ $ cat /proc/cmdline
coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1  smsc95xx.macaddr=E4:5F:01:95:E2:04 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=ttyS0,115200 console=tty1 root=PARTUUID=ac13a612-02 rootfstype=ext4 fsck.repair=yes rootwait
```

Googling a bit, I think the vc_mem stuff might be significant here. There is also a gpu_sched kernel module, which perhaps is related to this.

**Comment by m1hah** [comment]
Hi, thank you for everything.

The problem is with dietpi and missing dependencies.

First, dietpi headless was missing gpu drivers. Now that this is fixed, I'm missing ffmpeg and it can't start. I have installed it but ffmpeg can't be reached, the process is halted due to this.

I will install the Raspbian and get over with all the issues. 😀 

Thank you!

**Comment by SimonKagstrom** [comment]
Nice!

But ffmpeg should be part of the docker image, so I don't think that should be a problem?

**Comment by m1hah** [comment]
That is weird, the process was stuck on this part:

--> 
```
root | 1894 | 1861 | 26 | 15:39 | ? | 00:00:02 | /usr/bin/ffmpeg -loglevel info -i /app/staging/processing/2022-08-15_16-40-38/2022-08-15_16-29-46-left_repeater.mp4 -i /app/staging/processing/2022-08-15_16-40-38/2022-08-15_16-29-46-front.mp4 -i /app/staging/processing/2022-08-15_16-40-38/2022-08-15_16-29-46-right_repeater.mp4 -i /app/staging/processing/2022-08-15_16-40-38/2022-08-15_16-29-46-back.mp4 -filter_complex color=duration=59.78:s=1920x1920:c=black, fps=33 [base];[0:v] setpts=PTS-STARTPTS, scale=640x480 , hflip [left];[1:v] setpts=PTS-STARTPTS, scale=1920x1440 [front];[2:v] setpts=PTS-STARTPTS, scale=640x480 , hflip [right];[3:v] setpts=PTS-STARTPTS, scale=640x480 , hflip [rear];[base][left] overlay=eof_action=pass:repeatlast=0:x=0:y=1440 [left1];[left1][front] overlay=eof_action=pass:repeatlast=0:x=0:y=0 [front1];[front1][right] overlay=eof_action=pass:repeatlast=0:x=1280:y=1440 [right1];[right1][rear] overlay=eof_action=pass:repeatlast=0:x=640:y=1440 [rear1];[rear1] drawtext=fontfile=/usr/share/fonts/truetype/freefont/FreeSans.ttf:fontcolor=white:fontsize=48:borderw=2:bordercolor=black@1.0:x=(w/2-text_w/2):y=(h-(text_h)-10):text='"08/15/22 16\:40\:03 Celje"' [tmp0] -map [tmp0] -preset medium -crf 20 -b:v 30000K -c:v h264_omx -metadata creation_time=2022-08-15T14:29:46.000000Z -metadata description=Created by tesla_dashcam v0.1.19 -metadata title=SENTRY: 08/15/22 16:40:03 -y /app/staging/work/2022-08-15T16-29-46.mp4
```
This is different than when I was running dietpi in headless mode. It appears the docker can't find ffmpeg. 
After this process, CPU usage is at 0% and stops.

cat /proc/cmdline returns almost identical config:
```
coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1  smsc95xx.macaddr=E4:5F:01:1B:17:CF vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  root=PARTUUID=df909cde-02 rootfstype=ext4 rootwait fsck.repair=yes net.ifnames=0 logo.nologo console=tty1
```

**Comment by SimonKagstrom** [comment]
If you run the shell in the docker image, can you run ffmpeg?

**Comment by m1hah** [comment]
Interesting, actually I can.
```
bash-5.0# ffmpeg
ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9.3.0 (Alpine 9.3.0)
```

I am reinstalling Raspberry OS now. Will be much easier to troubleshoot.

**Comment by m1hah** [comment]
Fixed.

Apparently, Dietpi cannot run with:
```
--layout WIDESCREEN --quality MEDIUM --fps 33
```

I haven't tried to remove those args after I enabled the proper GPU.

Thank you Simon!

**Comment by SimonKagstrom** [comment]
Good to hear that you found it, and superb investigation!

It does sound like the last problem is caused by either Tesla dashcam or the Tesla dashcam manager script though. At least i can't see why dietpi would cause something like that?
