### ISSUE TITLE
RecentClips is unsupported

### ISSUE THREAD

**Issue by moro85** [SimonKagstrom/tesla_dashcam_manager#3]
It appears that the manager is only picking up files that contains 'event.json'
However, the recent clips does not contain such file, so it's not being converted

**Comment by SimonKagstrom** [comment]
You are right.  I'll see if I can fix that, probably by just looking at .mp4 files instead.

**Comment by SimonKagstrom** [comment]
Has been fixed with b40699a, I believe. I also tagged the docker images

simonkagstrom/tesla_dashcam_manager:4
simonkagstrom/tesla_dashcam_manager:latest

with these changes.
